# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Build Linux (x86_64)
      run:  GOOS=linux  GOARCH=amd64       go build -o moondeck

    - name: Build Linux (armv5, Raspberry Pi 1)
      run:  GOOS=linux  GOARCH=arm GOARM=5 go build -o moondeck.arm5

    - name: Build Linux (armv6, Raspberry Pi 2+)
      run:  GOOS=linux  GOARCH=arm GOARM=6 go build -o moondeck.arm6

    - name: Build macOS (Apple silicon)
      run : GOOS=darwin GOARCH=arm64       go build -o moondeck.macos

    - name: Build macOS (Intel)
      run:  GOOS=darwin GOARCH=amd64       go build -o moondeck.macosx86